name: Java CI

on:
  push:
    branches: master
  workflow_dispatch:

jobs:

  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run integration test with Failsafe
      run: mvn integration-test

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: java-liberty-app # Provide only Docker image name, tag will be automatically set to latest
        dockerfile: Dockerfile
        image-tag: ${{github.run_number}}
    
  deployment-update:
    runs-on: ubuntu-latest
    needs: ci-pipeline
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: lukaswb/gitops-demo
        event-type: deploy
        client-payload: '{"image": "docker.pkg.github.com/lukaswb/java-liberty-app/java-liberty-app:${{github.run_number}}"}'  
      
